"""
Law Enforcement Report Generator — PDF reports for scam intelligence.

Problem statement requirement #3: "Extracts bank details, UPI IDs & phishing links for law enforcement"
"""

import os
from datetime import datetime
from fpdf import FPDF


class HoneypotReport(FPDF):
    """Custom PDF report for law enforcement."""

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "SCAM INTELLIGENCE REPORT", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.cell(0, 6, "Generated by Agentic Honeypot System", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 6, f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S IST')}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | CONFIDENTIAL - Law Enforcement Use Only", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(41, 128, 185)
        self.set_text_color(255, 255, 255)
        self.cell(0, 8, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def key_value(self, key: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self.cell(55, 6, key + ":", new_x="END")
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 6, str(value), new_x="LMARGIN", new_y="NEXT")


async def generate_report(
    session_id: str,
    session_data: dict,
    messages: list[dict],
    intelligence: list[dict],
    output_dir: str = "reports",
) -> str:
    """Generate a PDF law enforcement report.

    Args:
        session_id: Session identifier
        session_data: Session metadata dict
        messages: List of message dicts
        intelligence: List of extracted intelligence dicts
        output_dir: Directory to save the report

    Returns:
        Path to generated PDF file
    """
    os.makedirs(output_dir, exist_ok=True)
    filename = f"scam_report_{session_id[:8]}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(output_dir, filename)

    pdf = HoneypotReport()
    pdf.alias_nb_pages()
    pdf.add_page()

    # === Session Summary ===
    pdf.section_title("1. SESSION SUMMARY")
    pdf.key_value("Session ID", session_id)
    pdf.key_value("Channel", session_data.get("channel", "message"))
    pdf.key_value("Status", session_data.get("status", "unknown"))
    pdf.key_value("Scam Type", session_data.get("scam_type", "unknown"))
    pdf.key_value("Scam Confidence", f"{session_data.get('scam_confidence', 0):.1%}")
    pdf.key_value("Hand-off Mode", session_data.get("handoff_mode", "user"))
    pdf.key_value("Total Messages", str(len(messages)))
    pdf.key_value("Session Started", session_data.get("created_at", "N/A"))
    pdf.key_value("Last Activity", session_data.get("updated_at", "N/A"))
    pdf.ln(5)

    # === Extracted Intelligence ===
    pdf.section_title("2. EXTRACTED INTELLIGENCE")

    if intelligence:
        # Table header
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_fill_color(220, 220, 220)
        pdf.cell(30, 7, "Type", border=1, fill=True, new_x="END")
        pdf.cell(70, 7, "Value", border=1, fill=True, new_x="END")
        pdf.cell(25, 7, "Confidence", border=1, fill=True, new_x="END")
        pdf.cell(65, 7, "Context", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 9)
        for item in intelligence:
            type_label = item.get("type", "unknown").upper()
            value = str(item.get("value", ""))[:35]
            confidence = f"{item.get('confidence', 0):.0%}"
            context = str(item.get("context", ""))[:30]

            # Color-code high-value intelligence
            if item.get("type") in ("upi", "bank_account", "phone"):
                pdf.set_fill_color(255, 230, 230)
            else:
                pdf.set_fill_color(255, 255, 255)

            pdf.cell(30, 6, type_label, border=1, fill=True, new_x="END")
            pdf.cell(70, 6, value, border=1, fill=True, new_x="END")
            pdf.cell(25, 6, confidence, border=1, fill=True, new_x="END")
            pdf.cell(65, 6, context, border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 8, "No intelligence extracted in this session.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # === Key Findings ===
    upi_ids = [i for i in intelligence if i.get("type") == "upi"]
    phones = [i for i in intelligence if i.get("type") == "phone"]
    urls = [i for i in intelligence if i.get("type") == "url"]
    accounts = [i for i in intelligence if i.get("type") == "bank_account"]

    if any([upi_ids, phones, urls, accounts]):
        pdf.section_title("3. KEY FINDINGS")
        if upi_ids:
            pdf.key_value("UPI IDs", ", ".join(i["value"] for i in upi_ids))
        if phones:
            pdf.key_value("Phone Numbers", ", ".join(i["value"] for i in phones))
        if urls:
            pdf.key_value("Phishing URLs", ", ".join(i["value"] for i in urls))
        if accounts:
            pdf.key_value("Bank Accounts", ", ".join(i["value"] for i in accounts))
        pdf.ln(5)

    # === Conversation Transcript ===
    pdf.section_title("4. CONVERSATION TRANSCRIPT")
    pdf.set_font("Helvetica", "", 9)

    for msg in messages:
        sender = msg.get("sender", "unknown").upper()
        text = msg.get("text", "")
        timestamp = msg.get("timestamp", "")

        if sender == "SCAMMER":
            pdf.set_text_color(200, 50, 50)
            label = "SCAMMER"
        else:
            pdf.set_text_color(50, 50, 200)
            label = "HONEYPOT"

        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 5, f"[{timestamp}] {label}:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 5, text, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    # === Disclaimer ===
    pdf.add_page()
    pdf.section_title("5. LEGAL DISCLAIMER")
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 5,
        "This report is generated automatically by the Agentic Honeypot System for the purpose of "
        "documenting potential scam/fraud activity. The information contained herein is extracted from "
        "conversations with suspected scam operators using AI-driven analysis.\n\n"
        "This report should be used by law enforcement agencies as supplementary evidence and should be "
        "corroborated with independent investigation. The extracted intelligence (UPI IDs, phone numbers, "
        "bank account details, URLs) represents data shared by the suspected scammer during the honeypot "
        "interaction.\n\n"
        "All conversations were conducted with informed consent under applicable cybersecurity regulations.",
        new_x="LMARGIN", new_y="NEXT",
    )

    pdf.output(filepath)
    return filepath
